# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vidtag.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vidtag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvidtag.proto\x12\x06vidtag\"\x1c\n\x0c\x42\x61tchRequest\x12\x0c\n\x04urls\x18\x01 \x03(\t\"\x82\x01\n\x0bVideoResult\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x12\n\nbrand_safe\x18\x04 \x01(\x08\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x0f\n\x07summary\x18\x06 \x01(\t\x12\r\n\x05\x65rror\x18\x07 \x01(\t\"5\n\rBatchResponse\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.vidtag.VideoResult2L\n\rVidTagService\x12;\n\x0c\x41nalyzeBatch\x12\x14.vidtag.BatchRequest\x1a\x15.vidtag.BatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vidtag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCHREQUEST']._serialized_start=24
  _globals['_BATCHREQUEST']._serialized_end=52
  _globals['_VIDEORESULT']._serialized_start=55
  _globals['_VIDEORESULT']._serialized_end=185
  _globals['_BATCHRESPONSE']._serialized_start=187
  _globals['_BATCHRESPONSE']._serialized_end=240
  _globals['_VIDTAGSERVICE']._serialized_start=242
  _globals['_VIDTAGSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
